-- Migration: Create saved_charts table for analytics
-- This table stores chart configurations generated by the analytics agent

-- Create saved_charts table
CREATE TABLE IF NOT EXISTS saved_charts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    institution_id UUID NOT NULL REFERENCES institutions(id) ON DELETE CASCADE,
    chart_config JSONB NOT NULL,
    title TEXT NOT NULL,
    description TEXT DEFAULT '',
    is_pinned BOOLEAN DEFAULT false,
    created_by UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_saved_charts_institution_id ON saved_charts(institution_id);
CREATE INDEX IF NOT EXISTS idx_saved_charts_is_pinned ON saved_charts(institution_id, is_pinned) WHERE is_pinned = true;
CREATE INDEX IF NOT EXISTS idx_saved_charts_created_at ON saved_charts(institution_id, created_at DESC);

-- Add trigger to update updated_at
CREATE OR REPLACE FUNCTION update_saved_charts_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_saved_charts_updated_at ON saved_charts;
CREATE TRIGGER trigger_saved_charts_updated_at
    BEFORE UPDATE ON saved_charts
    FOR EACH ROW
    EXECUTE FUNCTION update_saved_charts_updated_at();

-- Enable RLS
ALTER TABLE saved_charts ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Allow institution members to view charts
CREATE POLICY "Institution members can view saved charts"
    ON saved_charts FOR SELECT
    USING (
        institution_id IN (
            SELECT institution_id FROM institution_members
            WHERE user_id = auth.uid()
        )
    );

-- Allow admins to insert charts
CREATE POLICY "Admins can insert saved charts"
    ON saved_charts FOR INSERT
    WITH CHECK (
        institution_id IN (
            SELECT institution_id FROM institution_members
            WHERE user_id = auth.uid() AND role = 'admin'
        )
    );

-- Allow admins to update charts
CREATE POLICY "Admins can update saved charts"
    ON saved_charts FOR UPDATE
    USING (
        institution_id IN (
            SELECT institution_id FROM institution_members
            WHERE user_id = auth.uid() AND role = 'admin'
        )
    );

-- Allow admins to delete charts
CREATE POLICY "Admins can delete saved charts"
    ON saved_charts FOR DELETE
    USING (
        institution_id IN (
            SELECT institution_id FROM institution_members
            WHERE user_id = auth.uid() AND role = 'admin'
        )
    );

-- Add comment
COMMENT ON TABLE saved_charts IS 'Stores analytics chart configurations generated by the analytics agent';
COMMENT ON COLUMN saved_charts.chart_config IS 'Recharts-compatible chart configuration JSON (type, title, data, xKey, yKey, colors)';
COMMENT ON COLUMN saved_charts.is_pinned IS 'Whether the chart should appear on the main analytics dashboard';
